### ISSUE TITLE
How to start a new project section

### ISSUE THREAD

**Issue by tracykteal** [ctb/titus-blog#7]
Maybe retitle the "Reproducible Computational Analysis - How to start a new project" section. When I think of starting a new project, I think of organizing the project, like in Noble's 'A Quick Guide to Organizing Computational Biology' paper http://www.ncbi.nlm.nih.gov/pmc/articles/PMC2709440/ Maybe instead "Reproducible Computational Analysis - Getting started with pipelines and automation" ?

**Comment by ctb** [comment]
On Tue, Mar 31, 2015 at 08:49:26PM -0700, Tracy Teal wrote:
> Maybe retitle the "Reproducible Computational Analysis - How to start a new project" section. When I think of starting a new project, I think of organizing the project, like in Noble's 'A Quick Guide to Organizing Computational Biology' paper http://www.ncbi.nlm.nih.gov/pmc/articles/PMC2709440/ Maybe instead "Reproducible Computational Analysis - Getting started with pipelines and automation" ?

That was the title of the workshop I actually ran, tho - it's not a section
in the blog post.
